//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxyWatchApp.Resources {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalaxyWatchApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GalaxyWatchApp.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GalaxyWatchApp.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to can not register the event.
        /// </summary>
        public static string ExceptionEventNotRegister
        {
            get
            {
                return ResourceManager.GetString("ExceptionEventNotRegister", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to can not unregister the event.
        /// </summary>
        public static string ExceptionEventNotUnregister
        {
            get
            {
                return ResourceManager.GetString("ExceptionEventNotUnregister", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to CardsList.
        /// </summary>
        public static string CardsListPageTitle {
            get {
                return ResourceManager.GetString("CardsListPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string CardDetailsPageBottomText
        {
            get
            {
                return ResourceManager.GetString("CardDetailsPageBottomText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Bottom value.
        /// </summary>
        public static string CardDetailsPageBottomValue
        {
            get
            {
                return ResourceManager.GetString("CardDetailsPageBottomValue", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string CardDetailsPageLeftText
        {
            get
            {
                return ResourceManager.GetString("CardDetailsPageLeftText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Left unit.
        /// </summary>
        public static string CardDetailsPageLeftUnit
        {
            get
            {
                return ResourceManager.GetString("CardDetailsPageLeftUnit", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Left value.
        /// </summary>
        public static string CardDetailsPageLeftValue
        {
            get
            {
                return ResourceManager.GetString("CardDetailsPageLeftValue", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string CardDetailsPageRightText
        {
            get
            {
                return ResourceManager.GetString("CardDetailsPageRightText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Right unit.
        /// </summary>
        public static string CardDetailsPageRightUnit
        {
            get
            {
                return ResourceManager.GetString("CardDetailsPageRightUnit", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Right value.
        /// </summary>
        public static string CardDetailsPageRightValue
        {
            get
            {
                return ResourceManager.GetString("CardDetailsPageRightValue", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string CardDetailsPageTopText
        {
            get
            {
                return ResourceManager.GetString("CardDetailsPageTopText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to CardDetails.
        /// </summary>
        public static string CardDetailsPageTitle {
            get {
                return ResourceManager.GetString("CardDetailsPageTitle", resourceCulture);
            }
        }
    }
}
